Yaqoot/src/main/java/org/D7noun/model/SellingCard.java
package org.D7noun.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

@Entity
public class SellingCard implements Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id", updatable = false, nullable = false)
	private Long id;
	@Version
	@Column(name = "version")
	private int version;

	@Column
	@Temporal(TemporalType.DATE)
	private Date sellingDate;

	@Column
	private double sellingPrice;

	@Column
	private double discountPrice;

	@Column
	@OneToMany(mappedBy = "sellingCard", cascade = CascadeType.MERGE, orphanRemoval = true, fetch = FetchType.EAGER)
	private Set<Item> items = new HashSet<Item>();

	@ManyToOne
	private Buyer buyer;

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the version
	 */
	public int getVersion() {
		return version;
	}

	/**
	 * @param version
	 *            the version to set
	 */
	public void setVersion(int version) {
		this.version = version;
	}

	/**
	 * @return the sellingDate
	 */
	public Date getSellingDate() {
		return sellingDate;
	}

	/**
	 * @param sellingDate
	 *            the sellingDate to set
	 */
	public void setSellingDate(Date sellingDate) {
		this.sellingDate = sellingDate;
	}

	/**
	 * @return the sellingPrice
	 */
	public double getSellingPrice() {
		return sellingPrice;
	}

	/**
	 * @param sellingPrice
	 *            the sellingPrice to set
	 */
	public void setSellingPrice(double sellingPrice) {
		this.sellingPrice = sellingPrice;
	}

	/**
	 * @return the discountPrice
	 */
	public double getDiscountPrice() {
		return discountPrice;
	}

	/**
	 * @param discountPrice
	 *            the discountPrice to set
	 */
	public void setDiscountPrice(double discountPrice) {
		this.discountPrice = discountPrice;
	}

	/**
	 * @return the items
	 */
	public Set<Item> getItems() {
		return items;
	}

	/**
	 * @param items
	 *            the items to set
	 */
	public void setItems(Set<Item> items) {
		this.items = items;
	}

	/**
	 * @return the buyer
	 */
	public Buyer getBuyer() {
		return buyer;
	}

	/**
	 * @param buyer
	 *            the buyer to set
	 */
	public void setBuyer(Buyer buyer) {
		this.buyer = buyer;
	}

	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((buyer == null) ? 0 : buyer.hashCode());
		long temp;
		temp = Double.doubleToLongBits(discountPrice);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((items == null) ? 0 : items.hashCode());
		result = prime * result + ((sellingDate == null) ? 0 : sellingDate.hashCode());
		temp = Double.doubleToLongBits(sellingPrice);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + version;
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SellingCard other = (SellingCard) obj;
		if (buyer == null) {
			if (other.buyer != null)
				return false;
		} else if (!buyer.equals(other.buyer))
			return false;
		if (Double.doubleToLongBits(discountPrice) != Double.doubleToLongBits(other.discountPrice))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (items == null) {
			if (other.items != null)
				return false;
		} else if (!items.equals(other.items))
			return false;
		if (sellingDate == null) {
			if (other.sellingDate != null)
				return false;
		} else if (!sellingDate.equals(other.sellingDate))
			return false;
		if (Double.doubleToLongBits(sellingPrice) != Double.doubleToLongBits(other.sellingPrice))
			return false;
		if (version != other.version)
			return false;
		return true;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "SellingCard [id=" + id + ", version=" + version + ", sellingDate=" + sellingDate + ", sellingPrice="
				+ sellingPrice + ", discountPrice=" + discountPrice + ", items=" + items + ", buyer=" + buyer + "]";
	}

}

Yaqoot/src/main/java/org/D7noun/view/ItemBean.java
package org.D7noun.view;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.ejb.EJB;
import javax.ejb.Stateful;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.PhaseId;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import org.D7noun.facade.ItemAttachmentFacade;
import org.D7noun.facade.SettingsFacade;
import org.D7noun.model.Factory;
import org.D7noun.model.Item;
import org.D7noun.model.ItemAttachment;
import org.D7noun.model.SellingCard;
import org.D7noun.model.Settings;
import org.D7noun.model.Item.ItemState;
import org.omnifaces.util.Faces;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;

/**
 * Backing bean for Item entities.
 * <p/>
 * This class provides CRUD functionality for all Item entities. It focuses
 * purely on Java EE 6 standards (e.g. <tt>&#64;ConversationScoped</tt> for
 * state management, <tt>PersistenceContext</tt> for persistence,
 * <tt>CriteriaBuilder</tt> for searches) rather than introducing a CRUD
 * framework or custom base class.
 */

@Named
@Stateful
@ConversationScoped
public class ItemBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@EJB
	private SettingsFacade settingsFacade;

	/*
	 * Support creating and retrieving Item entities
	 */

	private Long id;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	private Item item;

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@Inject
	private Conversation conversation;

	@PersistenceContext(unitName = "yaqoot-pu", type = PersistenceContextType.EXTENDED)
	private EntityManager entityManager;

	public String create() {

		this.conversation.begin();
		this.conversation.setTimeout(1800000L);
		return "create?faces-redirect=true";
	}

	public void retrieve() {

		if (FacesContext.getCurrentInstance().isPostback()) {
			return;
		}

		if (this.conversation.isTransient()) {
			this.conversation.begin();
			this.conversation.setTimeout(1800000L);
		}

		if (this.id == null) {
			this.item = this.example;
		} else {
			this.item = findById(getId());
		}
	}

	public Item findById(Long id) {

		return this.entityManager.find(Item.class, id);
	}

	/*
	 * Support updating and deleting Item entities
	 */

	public String update() {
		this.conversation.end();

		try {
			if (this.id == null) {
				this.entityManager.persist(this.item);
				return "search?faces-redirect=true";
			} else {
				this.entityManager.merge(this.item);
				return "create?faces-redirect=true&id=" + this.item.getId();
			}
		} catch (Exception e) {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
			return null;
		}
	}

	public String delete() {
		this.conversation.end();

		try {
			Item deletableEntity = findById(getId());
			SellingCard sellingCard = deletableEntity.getSellingCard();
			if (sellingCard != null) {
				sellingCard.getItems().remove(deletableEntity);
				deletableEntity.setSellingCard(null);
				this.entityManager.merge(sellingCard);
			}
			this.entityManager.remove(deletableEntity);
			this.entityManager.flush();
			return "search?faces-redirect=true";
		} catch (Exception e) {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
			return null;
		}
	}

	/*
	 * Support searching Item entities with pagination
	 */

	private int page;
	private long count;
	private List<Item> pageItems;

	private Item example = new Item();

	public int getPage() {
		return this.page;
	}

	public void setPage(int page) {
		this.page = page;
	}

	public int getPageSize() {
		return 10;
	}

	public Item getExample() {
		return this.example;
	}

	public void setExample(Item example) {
		this.example = example;
	}

	public String search() {
		this.page = 0;
		return null;
	}

	public void paginate() {

		CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();

		// Populate this.count

		CriteriaQuery<Long> countCriteria = builder.createQuery(Long.class);
		Root<Item> root = countCriteria.from(Item.class);
		countCriteria = countCriteria.select(builder.count(root)).where(getSearchPredicates(root));
		this.count = this.entityManager.createQuery(countCriteria).getSingleResult();

		// Populate this.pageItems

		CriteriaQuery<Item> criteria = builder.createQuery(Item.class);
		root = criteria.from(Item.class);
		TypedQuery<Item> query = this.entityManager.createQuery(criteria.select(root).where(getSearchPredicates(root)));
		query.setFirstResult(this.page * getPageSize()).setMaxResults(getPageSize());
		this.pageItems = query.getResultList();
	}

	private Predicate[] getSearchPredicates(Root<Item> root) {

		CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();
		List<Predicate> predicatesList = new ArrayList<Predicate>();

		String barcode = this.example.getBarcode();
		if (barcode != null && !"".equals(barcode)) {
			predicatesList
					.add(builder.like(builder.lower(root.<String>get("barcode")), '%' + barcode.toLowerCase() + '%'));
		}
		String types = this.example.getTypes();
		if (types != null && !"".equals(types)) {
			predicatesList.add(builder.like(builder.lower(root.<String>get("types")), '%' + types.toLowerCase() + '%'));
		}
		String stockLocation = this.example.getStockLocation();
		if (stockLocation != null && !"".equals(stockLocation)) {
			predicatesList.add(builder.like(builder.lower(root.<String>get("stockLocation")),
					'%' + stockLocation.toLowerCase() + '%'));
		}
		ItemState itemState = this.example.getItemState();
		if (itemState != null && !"".equals(itemState)) {
			predicatesList.add(builder.equal(root.get("itemState"), itemState));
		}
		Factory factory = this.example.getFactory();
		if (factory != null) {
			predicatesList.add(builder.equal(root.get("factory"), factory));
		}

		return predicatesList.toArray(new Predicate[predicatesList.size()]);
	}

	public List<Item> getPageItems() {
		return this.pageItems;
	}

	public long getCount() {
		return this.count;
	}

	/*
	 * Support listing and POSTing back Item entities (e.g. from inside an
	 * HtmlSelectOneMenu)
	 */

	public List<Item> getAll() {

		CriteriaQuery<Item> criteria = this.entityManager.getCriteriaBuilder().createQuery(Item.class);
		return this.entityManager.createQuery(criteria.select(criteria.from(Item.class))).getResultList();
	}

	@SuppressWarnings("unchecked")
	public List<Item> getAllAvailableItems() {
		try {
			Query query = this.entityManager.createNamedQuery(Item.getAllItemsByState, Item.class);
			query.setParameter("itemState", ItemState.Available);
			return query.getResultList();
		} catch (Exception e) {
			e.printStackTrace();
			System.err.println("D7noun: getAllAvailableItems");
		}
		return null;
	}

	@SuppressWarnings("unchecked")
	public List<Item> getAllSoldItems() {
		try {
			Query query = this.entityManager.createNamedQuery(Item.getAllItemsByState, Item.class);
			query.setParameter("itemState", ItemState.Sold);
			return query.getResultList();
		} catch (Exception e) {
			e.printStackTrace();
			System.err.println("D7noun: getAllSoldItems");
		}
		return null;
	}

	@SuppressWarnings("unchecked")
	public List<Item> getAllItemsByBillId(Long billId) {
		try {
			Query query = this.entityManager.createNamedQuery(Item.getAllItemsByBillId, Item.class);
			query.setParameter("billId", billId);
			return query.getResultList();
		} catch (Exception e) {
			e.printStackTrace();
			System.err.println("D7noun: getAllItemsByBillId");
		}
		return null;
	}

	@SuppressWarnings("unchecked")
	public List<Item> getAllItemsByBuyerId(Long buyerId) {
		try {
			Query query = this.entityManager.createNamedQuery(Item.getAllItemsByBuyerId, Item.class);
			query.setParameter("buyerId", buyerId);
			return query.getResultList();
		} catch (Exception e) {
			e.printStackTrace();
			System.err.println("D7noun: getAllItemsByBuyerId");
		}
		return null;
	}

	/*
	 * Support adding children to bidirectional, one-to-many tables
	 */

	private Item add = new Item();

	public Item getAdd() {
		return this.add;
	}

	public Item getAdded() {
		Item added = this.add;
		this.add = new Item();
		return added;
	}

	/**
	 * 
	 * Start Attachments
	 * 
	 */

	public void handleFileUpload(FileUploadEvent event) {
		try {

			UploadedFile uploadedFile = event.getFile();

			ItemAttachment attachment = new ItemAttachment();
			attachment.setItem(item);
			attachment.setFileName(uploadedFile.getFileName());
			attachment.setSize(uploadedFile.getSize());
			attachment.setContentType(uploadedFile.getContentType());
			attachment.setData(uploadedFile.getContents());
			item.getItemAttachments().add(attachment);
		} catch (Exception e) {
			e.printStackTrace();
			System.err.println("ItemBean: handleFileUpload");
		}
	}

	public void download(ItemAttachment attachment) {
		try {

Yaqoot/src/main/webapp/sellingCard/create.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	template="/resources/scaffold/pageTemplate.xhtml"
	xmlns:p="http://primefaces.org/ui">

	<f:metadata>
		<f:viewParam name="id" value='#{sellingCardBean.id}' />
		<f:event type="preRenderView" listener='#{sellingCardBean.retrieve}' />
	</f:metadata>

	<ui:param name="pageTitle" value="Create Selling Card" />

	<ui:define name="header">
		Selling Card
	</ui:define>

	<ui:define name="subheader">
		<c:choose>
			<c:when test='#{!empty sellingCardBean.id}'>
				Edit existing Selling Card
			</c:when>
			<c:otherwise>
				Create a new Selling Card
			</c:otherwise>
		</c:choose>
	</ui:define>

	<ui:define name="footer" />

	<ui:define name="main">
		<h:form id="create">

			<h:outputStylesheet name="css/selectOneMenu.css" />

			<h:messages globalOnly="true" styleClass="error" />


			<div class="col-md-9">
				<div class="row">

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-3">
								<h:outputLabel styleClass="control-label"
									for="sellingCardBeanSellingCardBuyer" value="Buyer:" />
							</div>
							<div class="col-md-9">
								<p:selectOneMenu id="sellingCardBeanSellingCardBuyer"
									value="#{sellingCardBean.sellingCard.buyer}" filter="true"
									filterMatchMode="contains" converter="#{buyerConverter}">
									<f:selectItem />
									<f:selectItems value="#{buyerBean.all}" var="buyer"
										itemValue="#{buyer}" itemLabel="#{buyer.display()}" />
								</p:selectOneMenu>
								<h:message for="sellingCardBeanSellingCardBuyer"
									styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-3">
								<h:outputLabel styleClass="control-label"
									for="sellingCardBeanSellingCardSellingDate"
									value="Selling Date:" />
							</div>
							<div class="col-md-9">
								<p:calendar id="sellingCardBeanSellingCardSellingDate"
									value="#{sellingCardBean.sellingCard.sellingDate}"
									pattern="dd-MM-yyyy" />
								<h:message for="sellingCardBeanSellingCardSellingDate"
									styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-3">
								<h:outputLabel styleClass="control-label"
									for="sellingCardBeanSellingCardSellingPrice"
									value="Selling Price:" />
							</div>
							<div class="col-md-9">
								<p:inputNumber id="sellingCardBeanSellingCardSellingPrice"
									inputStyleClass="form-control"
									value="#{sellingCardBean.sellingPrice}" styleClass="money"
									symbol="$" symbolPosition="s" decimalSeparator="."
									thousandSeparator="," minValue="0" disabled="true" />
								<h:message for="sellingCardBeanSellingCardSellingPrice"
									styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-3">
								<h:outputLabel styleClass="control-label"
									for="sellingCardBeanSellingCardDiscountPrice"
									value="Discount Price:" />
							</div>
							<div class="col-md-9">
								<p:inputNumber id="sellingCardBeanSellingCardDiscountPrice"
									inputStyleClass="form-control"
									value="#{sellingCardBean.discountPrice}" styleClass="money"
									symbol="$" symbolPosition="s" decimalSeparator="."
									thousandSeparator="," minValue="0" disabled="true" />
								<h:message for="sellingCardBeanSellingCardDiscountPrice"
									styleClass="error" />
							</div>
						</div>
					</div>

				</div>
			</div>

			<div class="col-md-12">
				<div class="row">

					<p:pickList id="ItemsList"
						value="#{sellingCardBean.itemsListModel}" var="item"
						itemValue="#{item}" itemLabel="#{item.display()}"
						showSourceControls="true" showTargetControls="true"
						showCheckbox="true" responsive="true" showSourceFilter="true"
						showTargetFilter="true" filterMatchMode="contains"
						converter="#{itemConverter}">

						<f:facet name="sourceCaption">Available</f:facet>
						<f:facet name="targetCaption">Cart</f:facet>


						<p:ajax event="transfer" listener="#{sellingCardBean.onTransfer}"
							update="sellingCardBeanSellingCardSellingPrice sellingCardBeanSellingCardDiscountPrice" />

					</p:pickList>

				</div>
			</div>

			<div class="row">
				<div class="col-md-12">
					<div class="buttons">
						<h:commandLink value="Save" action='#{sellingCardBean.update}'
							styleClass="btn btn-primary" />
						<c:choose>
							<c:when test='#{!empty sellingCardBean.id}'>
								<h:link value="Cancel" outcome="view"
									styleClass="btn btn-warning">
									<f:param name="id" value='#{sellingCardBean.id}' />
								</h:link>

								<h:commandLink value="Delete" styleClass="btn btn-danger"
									onclick="PF('deleteDialogVar').show()">
									<f:ajax />
								</h:commandLink>
							</c:when>
							<c:otherwise>
								<h:link value="Cancel" outcome="search"
									styleClass="btn btn-warning" />
							</c:otherwise>
						</c:choose>
					</div>
				</div>
			</div>

			<script type="text/javascript" src="../resources/js/selectOneMenu.js" />
			<script type="text/javascript" src="../resources/js/calendar.js" />

			<p:dialog id="deleteDialog" draggable="false" closable="false"
				modal="true" height="50" width="330" resizable="false"
				widgetVar="deleteDialogVar">
				<f:facet name="header">
					<h:outputText value="Confirm Deletion????" />
				</f:facet>

				<h:commandLink value="Ok" action="#{sellingCardBean.delete}"
					styleClass="btn btn-danger popup-buttons">
				</h:commandLink>
				<h:commandLink styleClass="btn btn-warning popup-buttons"
					onclick="PF('deleteDialogVar').hide()">
					<h:outputText value="Cancel" />
					<f:ajax />
				</h:commandLink>
			</p:dialog>


		</h:form>
	</ui:define>

</ui:composition>

Yaqoot/src/main/webapp/sellingCard/search.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/resources/scaffold/pageTemplate.xhtml"
	xmlns:p="http://primefaces.org/ui">

	<f:metadata>
		<f:viewParam name="page" value='#{sellingCardBean.page}' />
		<f:event type="preRenderView" listener='#{sellingCardBean.paginate}' />
	</f:metadata>

	<ui:param name="pageTitle" value="Search Selling Cards" />

	<ui:define name="header">
		Selling Card
	</ui:define>

	<ui:define name="subheader">
		Search Selling Cards 
	</ui:define>

	<ui:define name="footer" />

	<ui:define name="main">
		<h:form id="search">

			<h:outputStylesheet name="css/selectOneMenu.css" />
			<h:panelGroup styleClass="search">

				<div class="row">
					<div class="col-md-6">

						<div class="form-group">
							<div class="col-md-5">
								<h:outputLabel for="sellingCardBeanExampleSellingDate"
									styleClass="control-label" value="Selling Date:" />
							</div>
							<div class="col-md-7">
								<p:calendar id="sellingCardBeanExampleSellingDate"
									value="#{sellingCardBean.example.sellingDate}"
									pattern="dd-MM-yyyy" />
							</div>
						</div>

						<div class="form-group">
							<div class="col-md-5">
								<h:outputLabel for="sellingCardBeanExampleBuyer"
									styleClass="control-label" value="Buyer:" />
							</div>
							<div class="col-md-7">
								<p:selectOneMenu id="sellingCardBeanExampleBuyer"
									value="#{sellingCardBean.example.buyer}" filter="contains"
									filterMatchMode="contains" converter="#{buyerConverter}">
									<f:selectItem />
									<f:selectItems value="#{buyerBean.all}" var="buyer"
										itemLabel="#{buyer.display()}" itemValue="#{buyer}" />
								</p:selectOneMenu>
							</div>
						</div>

						<div class="form-group">
							<div class="col-md-5">
								<h:outputLabel for="sellingCardBeanExampleItem"
									styleClass="control-label" value="Item:" />
							</div>
							<div class="col-md-7">
								<p:selectOneMenu id="sellingCardBeanExampleItem"
									value="#{sellingCardBean.searchedItem}" filter="contains"
									filterMatchMode="contains" converter="#{itemConverter}">
									<f:selectItem />
									<f:selectItems value="#{itemBean.allSoldItems}" var="item"
										itemLabel="#{item.display()}" itemValue="#{item}" />
								</p:selectOneMenu>
							</div>
						</div>

					</div>
				</div>

				<h:panelGroup styleClass="buttons">
					<h:commandLink value="Search" action='#{billBean.search}'
						styleClass="btn btn-primary" />
					<h:commandLink value="Create New" action='#{billBean.create}'
						styleClass="btn btn-primary" />
				</h:panelGroup>

			</h:panelGroup>

			<h:dataTable id="sellingCardBeanPageItems" styleClass="data-table"
				value="#{sellingCardBean.pageItems}" var="_item">
				<h:column>
					<f:facet name="header">
						<h:outputText value="Selling Date" />
					</f:facet>
					<h:link outcome="/sellingCard/create">
						<f:param name="id" value="#{_item.id}" />
						<h:outputText id="_itemSellingDate" value="#{_item.sellingDate}">
							<f:convertDateTime type="date" />
						</h:outputText>
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Selling Price" />
					</f:facet>
					<h:link outcome="/sellingCard/create">
						<f:param name="id" value="#{_item.id}" />
						<h:outputText id="_itemSellingPrice" value="#{_item.sellingPrice}" />
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Discount Price" />
					</f:facet>
					<h:link outcome="/sellingCard/create">
						<f:param name="id" value="#{_item.id}" />
						<h:outputText id="_itemDiscountPrice"
							value="#{_item.discountPrice}" />
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Buyer" />
					</f:facet>
					<h:link outcome="/sellingCard/create">
						<f:param name="id" value="#{_item.id}" />
						<h:outputText id="_itemBuyer" value="#{_item.buyer.display()}" />
					</h:link>
				</h:column>
			</h:dataTable>
			<ui:include src="/resources/scaffold/paginator.xhtml">
				<ui:param name="paginatorBean" value='#{sellingCardBean}' />
			</ui:include>

			<h:outputScript name="js/calendar.js" />
			<h:outputScript name="js/selectOneMenu.js" />
		</h:form>

	</ui:define>

</ui:composition>